import Head from 'next/head'
import Image from 'next/image'
import Featured from '../components/Featured/Featured';
import ProductList from '../components/ProductList/ProductList';
import styles from "../styles/Home.module.css";
import axios from "axios";
import { Grid } from '@mui/material';
import { pizzas } from '../dummyData';





export default function Home({productList}) {

  
  return (
    
    <div className={styles.container}>
      <Head>
        <title>Ready Chow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
<style data-href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,200&display=swap" rel="stylesheet">

</style>
      </Head>
      <Featured/>

      <ProductList productList={productList}/>


    </div>
  )
}


export const getServerSideProps = async (ctx) => {
  // const myCookie = ctx.req?.cookies || "";
  // let admin = false;
  // if (myCookie.token === process.env.TOKEN) {
  //   admin = true;
  // }
  const res = await axios.get(
    "https://dull-gray-sparrow.cyclic.app/api/products"
  );  

  const products =  res.data
  return {
    props: {
      productList:  products,
    },
  };
};
