import Head from 'next/head'
import Image from 'next/image'
import styles from "../styles/Home.module.css";



export default function Home() {
  return (
    
    <div className={styles.container}>
      <Head>
        <title>Ready Chow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
<style data-href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,200&display=swap" rel="stylesheet">

</style>
    
      </Head>
    </div>
  )
}
